# Generated by Django 3.1.7 on 2021-03-18 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 18, 18, 6, 0, 324774), verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
