# Generated by Django 3.1.7 on 2021-03-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_collection_comments_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='article_tag',
            field=models.ManyToManyField(blank=True, related_name='article_tag', to='blog.Article'),
        ),
    ]
